apiVersion: installation.mattermost.com/v1beta1
kind: Mattermost
metadata:
  name: mm-full                         # Chose the desired name
spec:
  size: 100users                               # Adjust to your requirements
  ingress:
    enabled: true
    host: mattermost.example.com        # Adjust to your domain
    annotations:
      kubernetes.io/ingress.class: nginx
  version: 6.0.1
  licenseSecret: ""    
