kind: Probe
apiVersion: monitoring.coreos.com/v1
metadata:
  name: ziro-website
  namespace: monitoring
spec:
  interval: 60s
  module: http_2xx
  prober:
    url: blackbox-exporter.monitoring.svc.cluster.local:19115
  targets:
    staticConfig:
      static:
      - http://goziro.com
      - https://goziro.com
