---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: logging-loki
  namespace: logging
spec:
  allowCrossNamespaceImport: true
  datasource:
    access: proxy
    type: loki
    jsonData:
      timeInterval: 5s
      tlsSkipVerify: true
    name: loki-cluster
    url: http://loki.logging:3100
  instanceSelector:
    matchLabels:
      dashboards: grafana
